package com.wax.module.settings

/**
 * Every setting a user can override per target, with its value kind.
 *
 * Generated by tools/settings/generate_target_registry.py from the preference
 * screens. Do not hand-edit: a setting that is missing here cannot be
 * overridden, and one that is listed but no longer exists would show an empty
 * row in the interface. Regenerate instead.
 *
 * 123 settings, of which 89 are toggles.
 *
 * 20 settings are excluded on purpose: the module's own appearance and diagnostics,
 * and anything holding a credential or a file path.
 */
object SettingKeyRegistry {
    /** One setting, as the interface needs it. */
    data class Entry(
        val key: String,
        val kind: Kind,
        val category: String,
        /** The preference screen the setting is edited on. */
        val screen: String,
        /** Title string resource id, or 0 when the screen declares no title. */
        val titleRes: Int,
    ) {
        /** Whether this setting can be resolved to a plain on/off value. */
        val isToggle: Boolean get() = kind == Kind.BOOLEAN
    }

    /** The value kinds a preference can hold. */
    enum class Kind {
        BOOLEAN,
        TEXT,
        INT,
        FLOAT,
        SET,
    }

    private val ALL: List<Entry> =
        listOf(
            Entry("admin_grp", Kind.BOOLEAN, "conversation", "fragment_customization", com.wax.module.R.string.show_admin_group_icon),
            Entry(
                "alertsticker",
                Kind.BOOLEAN,
                "stickers",
                "preference_general_conversation",
                com.wax.module.R.string.enable_confirmation_to_send_sticker,
            ),
            Entry("always_online", Kind.BOOLEAN, "home_screen", "fragment_privacy", com.wax.module.R.string.always_online),
            Entry("ampm", Kind.BOOLEAN, "general", "preference_general_home", com.wax.module.R.string.ampm),
            Entry("animation_emojis", Kind.BOOLEAN, "conversation", "fragment_customization", com.wax.module.R.string.animation_emojis),
            Entry("animation_list", Kind.TEXT, "general", "fragment_customization", com.wax.module.R.string.list_animations_home_screen),
            Entry(
                "antidisappearing",
                Kind.BOOLEAN,
                "conversation",
                "preference_general_conversation",
                com.wax.module.R.string.antidisappearing,
            ),
            Entry(
                "antieditmessages",
                Kind.BOOLEAN,
                "conversation",
                "preference_general_conversation",
                com.wax.module.R.string.show_edited_message_history,
            ),
            Entry("antirevoke", Kind.TEXT, "conversation", "preference_general_conversation", com.wax.module.R.string.antirevoke),
            Entry(
                "antirevokestatus",
                Kind.TEXT,
                "conversation",
                "preference_general_conversation",
                com.wax.module.R.string.antirevokestatus,
            ),
            Entry("audio_transcription", Kind.BOOLEAN, "title_audio", "fragment_media", com.wax.module.R.string.audio_transcription),
            Entry("audio_type", Kind.TEXT, "title_audio", "fragment_media", com.wax.module.R.string.send_audio_as_voice_audio_note),
            Entry("autonext_status", Kind.BOOLEAN, "status", "fragment_general", com.wax.module.R.string.disable_auto_status),
            Entry("background_color", Kind.INT, "general", "fragment_customization", com.wax.module.R.string.background_color),
            Entry("blueonreply", Kind.BOOLEAN, "conversation", "fragment_privacy", com.wax.module.R.string.blueonreply),
            Entry(
                "broadcast_tag",
                Kind.BOOLEAN,
                "conversation",
                "preference_general_conversation",
                com.wax.module.R.string.show_chat_broadcast_icon,
            ),
            Entry("bubble_color", Kind.BOOLEAN, "conversation", "fragment_customization", com.wax.module.R.string.change_bubble_colors),
            Entry("bubble_left", Kind.INT, "conversation", "fragment_customization", com.wax.module.R.string.bubble_left),
            Entry("bubble_right", Kind.INT, "conversation", "fragment_customization", com.wax.module.R.string.bubble_right),
            Entry(
                "buttonaction",
                Kind.BOOLEAN,
                "home_screen",
                "preference_general_homescreen",
                com.wax.module.R.string.show_menu_buttons_as_icons,
            ),
            Entry(
                "bypass_version_check",
                Kind.BOOLEAN,
                "general",
                "preference_general_home",
                com.wax.module.R.string.disable_version_check,
            ),
            Entry("call_block_contacts", Kind.TEXT, "calls", "fragment_privacy", com.wax.module.R.string.contact_block_list),
            Entry("call_info", Kind.BOOLEAN, "calls", "fragment_privacy", com.wax.module.R.string.additional_call_information),
            Entry("call_privacy", Kind.TEXT, "calls", "fragment_privacy", com.wax.module.R.string.call_blocker),
            Entry(
                "call_recording_enable",
                Kind.BOOLEAN,
                "call_recording_title",
                "fragment_media",
                com.wax.module.R.string.call_recording_enable,
            ),
            Entry(
                "call_recording_toast",
                Kind.BOOLEAN,
                "call_recording_title",
                "fragment_media",
                com.wax.module.R.string.call_recording_toast_title,
            ),
            Entry("call_type", Kind.TEXT, "calls", "fragment_privacy", com.wax.module.R.string.call_blocking_type),
            Entry("call_white_contacts", Kind.TEXT, "calls", "fragment_privacy", com.wax.module.R.string.contact_white_list),
            Entry(
                "calltype",
                Kind.BOOLEAN,
                "conversation",
                "preference_general_conversation",
                com.wax.module.R.string.selection_of_call_type,
            ),
            Entry(
                "capture_device",
                Kind.BOOLEAN,
                "conversation",
                "preference_general_conversation",
                com.wax.module.R.string.capture_device_title,
            ),
            Entry("change_dpi", Kind.TEXT, "general", "fragment_customization", com.wax.module.R.string.change_default_dpi),
            Entry("changecolor", Kind.BOOLEAN, "general", "fragment_customization", com.wax.module.R.string.colors_customization),
            Entry("changecolor_mode", Kind.TEXT, "general", "fragment_customization", com.wax.module.R.string.changecolor_mode),
            Entry("channels", Kind.BOOLEAN, "status", "fragment_customization", com.wax.module.R.string.disable_channels),
            Entry("chatfilter", Kind.TEXT, "home_screen", "preference_general_homescreen", com.wax.module.R.string.novofiltro),
            Entry("configui_mode", Kind.TEXT, "home_screen", "fragment_customization", com.wax.module.R.string.configui),
            Entry(
                "copy_selection_message",
                Kind.BOOLEAN,
                "conversation",
                "preference_general_conversation",
                com.wax.module.R.string.copy_selection_message_title,
            ),
            Entry("copystatus", Kind.BOOLEAN, "status", "fragment_general", com.wax.module.R.string.enable_copy_status),
            Entry("custom_filters", Kind.BOOLEAN, "general", "fragment_customization", com.wax.module.R.string.custom_appearance),
            Entry("custom_privacy_type", Kind.TEXT, "conversation", "fragment_privacy", com.wax.module.R.string.custom_privacy_per_contact),
            Entry("disable_ads", Kind.BOOLEAN, "general", "preference_general_home", com.wax.module.R.string.disable_ads),
            Entry(
                "disable_defemojis",
                Kind.BOOLEAN,
                "conversation",
                "preference_general_conversation",
                com.wax.module.R.string.disable_default_emojis,
            ),
            Entry(
                "disable_expiration",
                Kind.BOOLEAN,
                "general",
                "preference_general_home",
                com.wax.module.R.string.disable_whatsapp_expiration,
            ),
            Entry(
                "disable_profile_status",
                Kind.BOOLEAN,
                "home_screen",
                "preference_general_homescreen",
                com.wax.module.R.string.disable_status_in_the_profile_photo,
            ),
            Entry(
                "disable_sensor_proximity",
                Kind.BOOLEAN,
                "title_audio",
                "fragment_media",
                com.wax.module.R.string.disable_the_proximity_sensor,
            ),
            Entry(
                "disable_swipe_up_in_group",
                Kind.BOOLEAN,
                "conversation",
                "preference_general_conversation",
                com.wax.module.R.string.disable_swipe_up_in_group,
            ),
            Entry(
                "dotonline",
                Kind.BOOLEAN,
                "home_screen",
                "preference_general_homescreen",
                com.wax.module.R.string.show_online_dot_in_conversation_list,
            ),
            Entry(
                "doubletap2like",
                Kind.BOOLEAN,
                "conversation",
                "preference_general_conversation",
                com.wax.module.R.string.double_click_to_react,
            ),
            Entry(
                "doubletap2like_emoji",
                Kind.TEXT,
                "conversation",
                "preference_general_conversation",
                com.wax.module.R.string.custom_reaction,
            ),
            Entry("download_local", Kind.TEXT, "download_title", "fragment_media", com.wax.module.R.string.local_download),
            Entry("downloadstatus", Kind.BOOLEAN, "download_title", "fragment_media", com.wax.module.R.string.statusdowload),
            Entry("downloadviewonce", Kind.BOOLEAN, "download_title", "fragment_media", com.wax.module.R.string.downloadviewonce),
            Entry("filter_items", Kind.TEXT, "general", "fragment_customization", com.wax.module.R.string.filter_items_by_id),
            Entry(
                "filtergroups",
                Kind.BOOLEAN,
                "home_screen",
                "preference_general_homescreen",
                com.wax.module.R.string.new_ui_group_filter,
            ),
            Entry("filterseen", Kind.BOOLEAN, "home_screen", "preference_general_homescreen", com.wax.module.R.string.enable_filter_chats),
            Entry(
                "floating_bottom_bar",
                Kind.BOOLEAN,
                "home_screen",
                "fragment_customization",
                com.wax.module.R.string.floating_bottom_bar,
            ),
            Entry(
                "floating_bottom_bar_radius",
                Kind.INT,
                "home_screen",
                "fragment_customization",
                com.wax.module.R.string.floating_bottom_bar_radius,
            ),
            Entry("floatingmenu", Kind.BOOLEAN, "conversation", "fragment_customization", com.wax.module.R.string.new_context_menu_ui),
            Entry("folder_theme", Kind.TEXT, "general", "fragment_customization", com.wax.module.R.string.theme_manager),
            Entry(
                "force_disable_emojis",
                Kind.BOOLEAN,
                "conversation",
                "preference_general_conversation",
                com.wax.module.R.string.force_disable_emojis,
            ),
            Entry(
                "force_restore_backup_feature",
                Kind.BOOLEAN,
                "general",
                "preference_general_home",
                com.wax.module.R.string.force_restore_backup,
            ),
            Entry("freezelastseen", Kind.BOOLEAN, "conversation", "fragment_privacy", com.wax.module.R.string.freezelastseen),
            Entry("ghostmode", Kind.BOOLEAN, "home_screen", "fragment_privacy", com.wax.module.R.string.ghost_mode_title),
            Entry("ghostmode_r", Kind.BOOLEAN, "conversation", "fragment_privacy", com.wax.module.R.string.ghostmode_r),
            Entry("ghostmode_t", Kind.BOOLEAN, "conversation", "fragment_privacy", com.wax.module.R.string.ghostmode),
            Entry(
                "google_translate",
                Kind.BOOLEAN,
                "conversation",
                "preference_general_conversation",
                com.wax.module.R.string.google_translate,
            ),
            Entry("hide_seen_view", Kind.BOOLEAN, "conversation", "fragment_privacy", com.wax.module.R.string.view_seen_tick),
            Entry("hideaudioseen", Kind.BOOLEAN, "conversation", "fragment_privacy", com.wax.module.R.string.hide_audio_seen),
            Entry("hideonceseen", Kind.BOOLEAN, "conversation", "fragment_privacy", com.wax.module.R.string.hide_once_view_seen),
            Entry("hideread", Kind.BOOLEAN, "conversation", "fragment_privacy", com.wax.module.R.string.hideread),
            Entry("hideread_group", Kind.BOOLEAN, "conversation", "fragment_privacy", com.wax.module.R.string.hideread_group),
            Entry("hidereceipt", Kind.BOOLEAN, "conversation", "fragment_privacy", com.wax.module.R.string.hidereceipt),
            Entry("hidestatusview", Kind.BOOLEAN, "status", "fragment_privacy", com.wax.module.R.string.hidestatusview),
            Entry("hidetabs", Kind.SET, "general", "fragment_customization", com.wax.module.R.string.hide_tabs_on_home),
            Entry("hidetag", Kind.BOOLEAN, "conversation", "preference_general_conversation", com.wax.module.R.string.hidetag),
            Entry("igstatus", Kind.BOOLEAN, "status", "fragment_customization", com.wax.module.R.string.igstatus_on_home_screen),
            Entry("imagequality", Kind.BOOLEAN, "title_image", "fragment_media", com.wax.module.R.string.imagequality),
            Entry(
                "jump_first_message",
                Kind.BOOLEAN,
                "conversation",
                "preference_general_conversation",
                com.wax.module.R.string.jump_first_message,
            ),
            Entry("lockedchats_enhancer", Kind.BOOLEAN, "home_screen", "fragment_privacy", com.wax.module.R.string.lockedchats_enhancer),
            Entry("media_preview", Kind.BOOLEAN, "other", "fragment_media", com.wax.module.R.string.enable_media_preview),
            Entry("menuwicon", Kind.BOOLEAN, "home_screen", "fragment_customization", com.wax.module.R.string.menuwicon),
            Entry("metaai", Kind.BOOLEAN, "home_screen", "preference_general_homescreen", com.wax.module.R.string.disable_metaai),
            Entry("newchat", Kind.BOOLEAN, "home_screen", "preference_general_homescreen", com.wax.module.R.string.enable_new_chat_button),
            Entry("oldstatus", Kind.BOOLEAN, "status", "fragment_customization", com.wax.module.R.string.old_statuses),
            Entry(
                "pinnedlimit",
                Kind.BOOLEAN,
                "conversation",
                "preference_general_conversation",
                com.wax.module.R.string.disable_pinned_limit,
            ),
            Entry("primary_color", Kind.INT, "general", "fragment_customization", com.wax.module.R.string.primary_color),
            Entry("proximity_audios", Kind.BOOLEAN, "title_audio", "fragment_media", com.wax.module.R.string.disable_audio_sensor),
            Entry(
                "remove_sticker_white_outline",
                Kind.BOOLEAN,
                "stickers",
                "preference_general_conversation",
                com.wax.module.R.string.remove_sticker_white_outline,
            ),
            Entry(
                "removechannel_rec",
                Kind.BOOLEAN,
                "status",
                "fragment_customization",
                com.wax.module.R.string.remove_channel_recomendations,
            ),
            Entry(
                "removeforwardlimit",
                Kind.BOOLEAN,
                "conversation",
                "preference_general_conversation",
                com.wax.module.R.string.removeforwardlimit,
            ),
            Entry(
                "removeseemore",
                Kind.BOOLEAN,
                "conversation",
                "preference_general_conversation",
                com.wax.module.R.string.remove_see_more_button,
            ),
            Entry(
                "revokeallmessages",
                Kind.BOOLEAN,
                "conversation",
                "preference_general_conversation",
                com.wax.module.R.string.delete_for_everyone_all_messages,
            ),
            Entry("seentick", Kind.TEXT, "conversation", "fragment_privacy", com.wax.module.R.string.show_button_to_send_blue_tick),
            Entry("segundos", Kind.BOOLEAN, "general", "preference_general_home", com.wax.module.R.string.segundosnahora),
            Entry("separategroups", Kind.BOOLEAN, "home_screen", "preference_general_homescreen", com.wax.module.R.string.separate_groups),
            Entry("show_dndmode", Kind.BOOLEAN, "home_screen", "preference_general_homescreen", com.wax.module.R.string.show_dnd_button),
            Entry(
                "show_freezeLastSeen",
                Kind.BOOLEAN,
                "home_screen",
                "fragment_privacy",
                com.wax.module.R.string.show_freezeLastSeen_button,
            ),
            Entry("showbiohome", Kind.BOOLEAN, "home_screen", "preference_general_homescreen", com.wax.module.R.string.showbio),
            Entry("shownamehome", Kind.BOOLEAN, "home_screen", "preference_general_homescreen", com.wax.module.R.string.showname),
            Entry(
                "showonline",
                Kind.BOOLEAN,
                "conversation",
                "preference_general_conversation",
                com.wax.module.R.string.show_toast_on_contact_online,
            ),
            Entry(
                "showonlinetext",
                Kind.BOOLEAN,
                "home_screen",
                "preference_general_homescreen",
                com.wax.module.R.string.show_online_last_seen_in_conversation_list,
            ),
            Entry(
                "stamp_copied_message",
                Kind.BOOLEAN,
                "conversation",
                "preference_general_conversation",
                com.wax.module.R.string.stamp_copied_messages,
            ),
            Entry("status_audio_studio", Kind.TEXT, "title_audio", "fragment_media", com.wax.module.R.string.status_audio_studio),
            Entry("status_style", Kind.TEXT, "status", "fragment_customization", com.wax.module.R.string.style_of_stories_status),
            Entry(
                "statuscomposer",
                Kind.BOOLEAN,
                "status",
                "fragment_customization",
                com.wax.module.R.string.custom_colors_for_text_status,
            ),
            Entry("tasker", Kind.BOOLEAN, "general", "preference_general_home", com.wax.module.R.string.enable_tasker_automation),
            Entry("text_color", Kind.INT, "general", "fragment_customization", com.wax.module.R.string.text_color),
            Entry("text_in_hour", Kind.TEXT, "general", "preference_general_home", com.wax.module.R.string.textonahora),
            Entry(
                "toast_viewed_message",
                Kind.BOOLEAN,
                "conversation",
                "preference_general_conversation",
                com.wax.module.R.string.toast_on_viewed_message,
            ),
            Entry("toast_viewed_status", Kind.BOOLEAN, "status", "fragment_general", com.wax.module.R.string.toast_on_viewed_status),
            Entry("toastdeleted", Kind.BOOLEAN, "conversation", "preference_general_conversation", com.wax.module.R.string.toast_on_delete),
            Entry("typearchive", Kind.TEXT, "home_screen", "fragment_privacy", com.wax.module.R.string.hide_archived_chat),
            Entry(
                "verify_blocked_contact",
                Kind.BOOLEAN,
                "conversation",
                "preference_general_conversation",
                com.wax.module.R.string.show_contact_added_status,
            ),
            Entry("video_limit_size", Kind.FLOAT, "title_video", "fragment_media", com.wax.module.R.string.increase_video_size_limit),
            Entry("video_maxfps", Kind.BOOLEAN, "title_video", "fragment_media", com.wax.module.R.string.send_video_in_60fps),
            Entry(
                "video_real_resolution",
                Kind.BOOLEAN,
                "title_video",
                "fragment_media",
                com.wax.module.R.string.send_video_in_real_resolution,
            ),
            Entry("videoquality", Kind.BOOLEAN, "title_video", "fragment_media", com.wax.module.R.string.videoquality),
            Entry("viewonce", Kind.BOOLEAN, "conversation", "fragment_privacy", com.wax.module.R.string.viewonce),
            Entry("voicenote_speed", Kind.FLOAT, "title_audio", "fragment_media", com.wax.module.R.string.voice_note_speed),
            Entry("wallpaper", Kind.BOOLEAN, "general", "fragment_customization", com.wax.module.R.string.wallpaper_in_home_screen),
            Entry("wallpaper_alpha", Kind.INT, "general", "fragment_customization", com.wax.module.R.string.wallpaper_transparency),
            Entry(
                "wallpaper_alpha_navigation",
                Kind.INT,
                "general",
                "fragment_customization",
                com.wax.module.R.string.navigation_transparency,
            ),
            Entry("wallpaper_alpha_toolbar", Kind.INT, "general", "fragment_customization", com.wax.module.R.string.toolbar_transparency),
        )

    /** Every overrideable setting. */
    val entries: List<Entry> = ALL

    private val BY_KEY: Map<String, Entry> = ALL.associateBy { it.key }

    /** The setting for [key], or null when it cannot be overridden. */
    fun find(key: String): Entry? = BY_KEY[key]

    /** Whether [key] can carry a per-target override. */
    fun isOverrideable(key: String): Boolean = BY_KEY.containsKey(key)

    /** The settings grouped by category, categories in alphabetical order. */
    fun byCategory(): Map<String, List<Entry>> = ALL.groupBy { it.category }.toSortedMap()

    /** The toggles, which is what the interface offers as a three-way control. */
    fun toggles(): List<Entry> = ALL.filter { it.isToggle }
}
