package com.wax.module.ui.fragments.base

import android.Manifest
import android.content.Intent
import android.content.SharedPreferences
import android.content.pm.PackageManager
import android.os.Build
import android.os.Bundle
import android.os.Environment
import android.util.TypedValue
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.activity.OnBackPressedCallback
import androidx.appcompat.app.AppCompatActivity
import androidx.core.content.ContextCompat
import androidx.preference.ListPreference
import androidx.preference.Preference
import androidx.preference.PreferenceCategory
import androidx.preference.PreferenceFragmentCompat
import androidx.preference.PreferenceGroup
import androidx.preference.PreferenceManager
import androidx.preference.SeekBarPreference
import androidx.recyclerview.widget.RecyclerView
import com.google.android.material.dialog.MaterialAlertDialogBuilder
import com.jaredrummler.android.colorpicker.ColorPreferenceCompat
import com.wax.module.AppLanguage
import com.wax.module.BuildConfig
import com.wax.module.ModuleApplication
import com.wax.module.R
import com.wax.module.activities.MainActivity
import com.wax.module.preference.FloatSeekBarPreference
import rikka.material.preference.MaterialSwitchPreference

abstract class BasePreferenceFragment :
    PreferenceFragmentCompat(),
    SharedPreferences.OnSharedPreferenceChangeListener {
    @JvmField
    protected var mPrefs: SharedPreferences? = null
    private var backPressedCallback: OnBackPressedCallback? = null

    private val prefs: SharedPreferences
        get() = checkNotNull(mPrefs)

    override fun onCreatePreferences(
        savedInstanceState: Bundle?,
        rootKey: String?,
    ) {
        mPrefs = PreferenceManager.getDefaultSharedPreferences(requireContext())
        prefs.registerOnSharedPreferenceChangeListener(this)
        // ViewPager2 keeps adjacent legacy fragments STARTED even while hidden.
        // Their callbacks must not consume Back until that fragment is RESUMED.
        val callback =
            object : OnBackPressedCallback(false) {
                override fun handleOnBackPressed() {
                    if (parentFragmentManager.backStackEntryCount > 0) {
                        parentFragmentManager.popBackStack()
                    } else if ((requireActivity() as? MainActivity)?.returnFromLegacyDestination() != true) {
                        requireActivity().finish()
                    }
                }
            }
        backPressedCallback = callback
        requireActivity().onBackPressedDispatcher.addCallback(this, callback)
    }

    /**
     * Fills the language list once the preference tree exists.
     *
     * Built here rather than declared as a resource array for two reasons: the first entry
     * is "System default", which has to appear in the reader's own language, and the
     * language names are each language's own name. A static array can do neither, and
     * `arrays.xml` is regenerated by the compatibility tooling, so anything declared there
     * would eventually be overwritten by a sync.
     */
    private fun populateLanguagePreference() {
        val preference = findPreference<ListPreference>(AppLanguage.KEY) ?: return
        val context = preference.context
        preference.entries =
            AppLanguage.entryLabels(context.getString(R.string.language_system_default))
        preference.entryValues = AppLanguage.entryValues()
        val selected = preference.value
        if (selected != AppLanguage.SYSTEM && !AppLanguage.isSupported(selected)) {
            // A language this build does not offer would otherwise stay selected while
            // showing an entry that is not in the list.
            preference.value = AppLanguage.SYSTEM
        }
    }

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?,
    ): View {
        applyReferencePreferenceStyle(preferenceScreen, R.drawable.ic_general)
        updatePreferenceStates(null)
        monitorPreference()
        return super.onCreateView(inflater, container, savedInstanceState)!!
    }

    private fun applyReferencePreferenceStyle(
        group: PreferenceGroup?,
        inheritedIcon: Int,
    ) {
        if (group == null) return

        for (index in 0 until group.preferenceCount) {
            val preference = group.getPreference(index)
            if (preference is PreferenceCategory) {
                val categoryIcon = PreferenceIconResolver.sectionIcon(preference.title, inheritedIcon)
                if (preference.icon == null) preference.setIcon(categoryIcon)
                preference.isIconSpaceReserved = true
                preference.layoutResource = R.layout.preference_card_category
                preference.isSelectable = false
                applyReferencePreferenceStyle(preference, categoryIcon)
                continue
            }

            if (preference.icon == null) {
                preference.setIcon(PreferenceIconResolver.preferenceIcon(preference, inheritedIcon))
            }
            preference.isIconSpaceReserved = true

            when (preference) {
                is MaterialSwitchPreference -> {
                    preference.layoutResource = R.layout.preference_feature_switch
                    preference.widgetLayoutResource = R.layout.preference_widget_material3_switch
                }

                is FloatSeekBarPreference -> {
                    preference.layoutResource = R.layout.preference_feature_seekbar
                }

                is SeekBarPreference -> {
                    preference.layoutResource = R.layout.preference_feature_standard_seekbar
                }

                is ColorPreferenceCompat -> {
                    preference.layoutResource = R.layout.preference_feature_color
                }

                else -> {
                    preference.layoutResource = R.layout.preference_feature_list
                }
            }
        }
    }

    override fun onViewCreated(
        view: View,
        savedInstanceState: Bundle?,
    ) {
        // Before this point the preference tree does not exist yet; after it, every
        // screen's own onCreatePreferences has run and the entries can be filled.
        populateLanguagePreference()
        super.onViewCreated(view, savedInstanceState)
    }

    override fun onResume() {
        populateLanguagePreference()
        super.onResume()
        backPressedCallback?.isEnabled = true
        setDisplayHomeAsUpEnabled(true)
    }

    override fun onPause() {
        backPressedCallback?.isEnabled = false
        super.onPause()
    }

    override fun onSharedPreferenceChanged(
        sharedPreferences: SharedPreferences,
        key: String?,
    ) {
        ModuleApplication.instance.sendBroadcast(Intent("${BuildConfig.APPLICATION_ID}.MANUAL_RESTART"))
        if (isAdded) updatePreferenceStates(key)
    }

    override fun onDestroy() {
        super.onDestroy()
        mPrefs?.unregisterOnSharedPreferenceChangeListener(this)
    }

    private fun monitorPreference() {
        findPreference<MaterialSwitchPreference>("downloadstatus")?.onPreferenceChangeListener =
            Preference.OnPreferenceChangeListener { _, newValue -> checkStoragePermission(newValue) }

        findPreference<MaterialSwitchPreference>("downloadviewonce")?.onPreferenceChangeListener =
            Preference.OnPreferenceChangeListener { _, newValue -> checkStoragePermission(newValue) }

        findPreference<MaterialSwitchPreference>("force_disable_emojis")?.onPreferenceChangeListener =
            Preference.OnPreferenceChangeListener { _, newValue ->
                if (newValue is Boolean && newValue) {
                    MaterialAlertDialogBuilder(requireContext())
                        .setTitle(R.string.force_disable_emojis_alert_title)
                        .setMessage(R.string.force_disable_emojis_alert_msg)
                        .setPositiveButton(android.R.string.ok, null)
                        .show()
                }
                true
            }
    }

    private fun checkStoragePermission(newValue: Any?): Boolean {
        if (newValue is Boolean && newValue) {
            val needsPermission =
                (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R && !Environment.isExternalStorageManager()) ||
                    (
                        Build.VERSION.SDK_INT < Build.VERSION_CODES.R &&
                            ContextCompat.checkSelfPermission(
                                requireContext(),
                                Manifest.permission.WRITE_EXTERNAL_STORAGE,
                            ) != PackageManager.PERMISSION_GRANTED
                    )
            if (needsPermission) {
                ModuleApplication.showRequestStoragePermission(requireActivity())
                return false
            }
        }
        return true
    }

    private fun updatePreferenceStates(key: String?) {
        PreferenceStateController(this, prefs).update(key)
    }

    fun setDisplayHomeAsUpEnabled(enabled: Boolean) {
        val actionBar = (activity as? AppCompatActivity)?.supportActionBar ?: return
        actionBar.setDisplayHomeAsUpEnabled(enabled)
    }

    /** Scroll to a preference by its key and briefly highlight it. */
    override fun scrollToPreference(preferenceKey: String) {
        view?.postDelayed({
            val preference = findPreference<Preference>(preferenceKey) ?: return@postDelayed
            super.scrollToPreference(preference)
            highlightPreference(preference)
        }, 100)
    }

    private fun highlightPreference(preference: Preference?) {
        view?.postDelayed({
            val recyclerView = listView ?: return@postDelayed
            val targetKey = preference?.key ?: return@postDelayed
            var found = false

            for (index in 0 until recyclerView.childCount) {
                val child = recyclerView.getChildAt(index)
                val holder = recyclerView.getChildViewHolder(child)
                if (holder is androidx.preference.PreferenceViewHolder) {
                    val position = holder.bindingAdapterPosition
                    if (position != RecyclerView.NO_POSITION) {
                        try {
                            val item = findPreferenceAtPosition(preferenceScreen, position)
                            if (item?.key == targetKey) {
                                animateHighlight(holder.itemView)
                                found = true
                                break
                            }
                        } catch (_: Exception) {
                        }
                    }
                }
            }

            if (!found) view?.postDelayed({ tryHighlightAgain(targetKey) }, 500)
        }, 500)
    }

    private fun tryHighlightAgain(targetKey: String) {
        val recyclerView = listView ?: return
        val child =
            (0 until recyclerView.childCount)
                .asSequence()
                .map(recyclerView::getChildAt)
                .filterIsInstance<ViewGroup>()
                .firstOrNull { candidate ->
                    val holder = recyclerView.getChildViewHolder(candidate)
                    if (holder !is androidx.preference.PreferenceViewHolder) return@firstOrNull false
                    val position = holder.bindingAdapterPosition
                    position != RecyclerView.NO_POSITION &&
                        findPreferenceAtPosition(preferenceScreen, position)?.key == targetKey
                }
        animateHighlight(child)
    }

    private fun findPreferenceAtPosition(
        group: PreferenceGroup?,
        targetPosition: Int,
    ): Preference? {
        if (group == null) return null

        var currentPosition = 0
        for (index in 0 until group.preferenceCount) {
            val preference = group.getPreference(index) ?: continue
            if (currentPosition == targetPosition) return preference
            currentPosition++

            if (preference is PreferenceGroup) {
                val childCount = countPreferences(preference)
                if (targetPosition < currentPosition + childCount) {
                    return findPreferenceAtPosition(preference, targetPosition - currentPosition)
                }
                currentPosition += childCount
            }
        }
        return null
    }

    private fun countPreferences(group: PreferenceGroup): Int {
        var count = 0
        for (index in 0 until group.preferenceCount) {
            val preference = group.getPreference(index)
            if (preference is PreferenceGroup) {
                count += countPreferences(preference)
            } else {
                count++
            }
        }
        return count
    }

    private fun animateHighlight(view: View?) {
        if (view == null || context == null) return

        val typedValue = TypedValue()
        view.context.theme.resolveAttribute(android.R.attr.colorPrimary, typedValue, true)
        val primaryColor = typedValue.data
        val highlightColor =
            android.graphics.Color.argb(
                51,
                android.graphics.Color.red(primaryColor),
                android.graphics.Color.green(primaryColor),
                android.graphics.Color.blue(primaryColor),
            )
        val originalBackground = view.background
        view.setBackgroundColor(highlightColor)
        view.postDelayed({
            if (originalBackground != null) {
                view.background = originalBackground
            } else {
                view.setBackgroundColor(android.graphics.Color.TRANSPARENT)
            }
        }, 1500)
    }
}
